platform:ios,'7.0'
pod 'ReactiveCocoa'
pod 'ReactiveViewModel'
pod 'AFNetworking'
pod 'JSONModel'
pod 'SVProgressHUD'
pod 'SVPullToRefresh'
pod 'SDWebImage'
pod 'Parse'
pod 'FDFullscreenPopGesture'
pod 'IQKeyboardManager'
pod 'TWMessageBarManager'
pod 'Masonry'
